# python numpy

In [1]:
lst=[1,2,3,4,5]
print(lst)


[1, 2, 3, 4, 5]


In [2]:
import numpy as np
lst = [1,2,3,4,5]
array = np.array(lst)
print(array)

[1 2 3 4 5]


In [8]:
lst =[1,2,3,4,5]
array = np.array(lst)
print(array.shape)
print(array.dtype)


(5,)
int64


In [10]:
lst =[1.5,2.5,3.5,4.5,5.5]
array = np.array(lst)
print(array.shape)
print(array.dtype)


(5,)
float64


In [16]:
a1 = np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
a1 = np.array([1 ,2, 3])
a2 = np.array([4 ,5, 6])
print((np.hstack((a1,a2))))


[1 2 3 4 5 6]


In [21]:
a1 = np.array([1 ,2, 3])
a2 = np.array([4 ,5, 6])
print((np.vstack((a1,a2))))

[[1 2 3]
 [4 5 6]]


In [22]:
a1 = np.random.normal([1 ,2, 3,5,6])
print(a1)

                      

[-0.42839426  1.44660603  4.68338545  3.15797124  5.76787472]


In [26]:
np.ones((5,6),dtype=np.int64)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [39]:
A = np.matrix(np.ones((4,4),dtype = np.int64))
np.asarray(A)[3] = 5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]]


In [42]:
A = np.matrix(np.ones((4,4),dtype = np.int64))
np.asarray(A)[1][3] = 14
np.asarray(A)[3][3] = 16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [45]:
A = np.matrix(np.ones((4,4),dtype = np.int64))
np.asarray(A)[1][3] = 14
np.asarray(A)[2][3] = 16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1 16]
 [ 1  1  1  1]]


In [47]:
import numpy as np
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [50]:
np.arange(2,20,2)


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [52]:
np.arange(1,21,1)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [54]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [56]:
np.arange(10,2,30)

array([], dtype=int64)

In [57]:
a1 = np.array([(1,2,3),(4,5,6)])
print("slicing coloumn : ",a1[:,1])

slicing coloumn :  [2 5]


In [58]:
a1 = np.array([(1,2,3),(4,5,6)])
print("slicing coloumn : ",a1[:,2])

slicing coloumn :  [3 6]


In [59]:
a1 = np.array([(1,2,3),(4,5,6)])
print("slicing coloumn : ",a1[:,0])

slicing coloumn :  [1 4]


In [62]:
a1 = np.array([(1,2,3),(4,5,6)])
print("slicing coloumn : ",a1[:,1])

slicing coloumn :  [2 5]


In [84]:
a1 = np.array([(1,2,3),(4,5,6)])
print("frist row : ",a1[0][0])
print("second row :",a1[0][1])
print("thired row :",a1[0][2])
print("column 2 :")
print("frist row : ",a1[1][0])
print("second row :",a1[1][1])
print("thired row :",a1[1][2])

frist row :  1
second row : 2
thired row : 3
column 2 :
frist row :  4
second row : 5
thired row : 6


In [85]:
a1 = np.random.normal(1,4,3)
print(a1)
print("min value = ",np.min(a1))
print("max value = ",np.max(a1))
print("mean value = ",np.mean(a1))
print("median value = ",np.median(a1))

[3.20196416 4.75607482 4.91830403]
min value =  3.2019641647311143
max value =  4.918304030055827
mean value =  4.292114338274486
median value =  4.756074820036519


In [89]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
np.dot(a1,a2)

32

In [94]:
a1 = np.array((1,2),[1,5])
a2 = np.array((4,5),(5,6))
np.dot(a1,a2)

TypeError: data type not understood